default: lint format check test

# Install dependencies
install:
    uv sync --locked

install-dev:
    uv sync --locked --dev

# Run linting checks
lint:
    uv run --locked ruff check src tests .github/scripts benchmarks

# Format code
format:
    uv run --locked ruff check --select I --fix src tests .github/scripts benchmarks
    uv run --locked ruff format src tests .github/scripts benchmarks

# Verify formatting without rewriting files (used by CI)
fmt-check:
    uv run --locked ruff format --check src tests .github/scripts benchmarks

# Run type checking
check:
    uv run --locked ty check src tests

# Run tests
test:
    uv run --locked pytest tests

# Run tests once, emitting both coverage XML and JUnit XML for Codecov
test-cov:
    uv run --locked pytest tests --cov=src/spxtacular --cov-report=xml --junit-xml=junit.xml

# Build and serve docs
docs:
    uv run --locked mkdocs serve --dev-addr=localhost:8003

# Build docs to site/
docs-build:
    uv run --locked mkdocs build --strict

# Report deconvolution reference accuracy and performance
benchmark:
    uv run --locked python benchmarks/deconvolution.py

# Export the editable PowerPoint graphical abstract as a publication-quality PNG
paper-figure:
    #!/usr/bin/env bash
    set -euo pipefail
    command -v libreoffice >/dev/null
    command -v pdftoppm >/dev/null
    paper_render_dir="$(mktemp -d)"
    trap 'rm -rf "$paper_render_dir"' EXIT
    libreoffice --headless --convert-to pdf --outdir "$paper_render_dir" paper/spxtacular_graphical_abstract.pptx >/dev/null
    pdftoppm -f 1 -singlefile -png -r 300 "$paper_render_dir/spxtacular_graphical_abstract.pdf" paper/figures/graphical_abstract >/dev/null

# Compile paper/paper.md with the official JOSS/Inara toolchain
paper-build:
    docker run --rm --volume "$PWD/paper:/data" --user "$(id -u):$(id -g)" --env JOURNAL=joss openjournals/inara

# Regenerate the figure and compile the JOSS draft
paper: paper-figure paper-build

# Count manuscript words using Pandoc from the same Inara image
paper-wordcount:
    @docker run --rm --volume "$PWD/paper:/data" --user "$(id -u):$(id -g)" --entrypoint pandoc openjournals/inara paper.md --from markdown --to plain | wc -w

# Show metadata for the latest generated JOSS PDF
paper-info:
    pdfinfo paper/paper.pdf

# Build and perform lightweight checks on the submission artifacts
paper-preflight: paper
    test -s paper/paper.pdf
    test -s paper/paper.bib
    test -s paper/spxtacular_graphical_abstract.pptx
    test -s paper/figures/graphical_abstract.png
    test paper/figures/graphical_abstract.png -nt paper/spxtacular_graphical_abstract.pptx
    @just paper-wordcount
    @pdfinfo paper/paper.pdf | sed -n '1,18p'

# Remove files generated by Inara; manuscript sources and figures are preserved
paper-clean:
    rm -f paper/paper.pdf
    rm -rf paper/jats
