#!/usr/bin/env python3
"""Check assets.json: the figures and tables the manuscript includes by id.

WHAT THIS REPLACED. Two whole-tree hashes in .assets-stamp, which fired on the
same failures this does and could only report "analysis/ has changed" -- without
naming which figure that ruins. They also fired on a new file no generator
imports, a change that by definition altered no output, so the check was
redundant where it was right and noisy where it was unique.

Per entry instead, which also sees a DATA input that changed -- something the
stamp structurally could not, since it skipped analysis/data/ and
analysis/results/ as heavy and usually untracked.

WHAT WENT WITH THEM, honestly. An input a generator READS without declaring or
importing is now invisible: this only knows what was declared plus what was
imported. The stamp caught that when the file happened to sit under analysis/
outside data/. In its place, _assets.record() warns when a generator declares no
inputs at all, so the omission is visible where it is made rather than silent.

INPUTS THAT ARE NOT PRESENT are reported as unverified, never as stale. Data
usually lives outside the repository, so on a fresh clone or in CI there is
nothing to hash -- and a person who does not have the data could not act on a
staleness report about it anyway.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import hashcache  # noqa: E402

ASSETS = ROOT / "assets.json"

# Where generated outputs live. An entry must point inside one of these, and a
# file in one of them that no entry claims is reported.
OUTPUT_DIRS = ("figures", "si")

CALL = re.compile(r'#?(?:fig|tbl)\(\s*"([^"]+)"')


class Finding:
    def __init__(self, level: str, id: str, msg: str) -> None:
        self.level, self.id, self.msg = level, id, msg

    def __str__(self) -> str:
        return f"  {self.level:<6} {self.id:<28} {self.msg}"


# Through the stat-keyed cache: declared inputs can be gigabytes, and this runs
# inside `just verify`, the gate that must cost nothing.
_sha = hashcache.sha


def _entry(id: str, rec: dict) -> list[Finding]:
    out: list[Finding] = []
    path = rec.get("path")
    if not path:
        return [Finding("error", id, "has no path")]
    target = ROOT / path

    if rec.get("kind") not in ("figure", "table"):
        out.append(Finding("error", id, f"has kind {rec.get('kind')!r}, "
                                        f"expected 'figure' or 'table'"))
    if not target.is_file():
        out.append(Finding("error", id,
            f"declares {path}, which does not exist -- run: just assets"))
        return out
    if not any(path.startswith(d + "/") for d in OUTPUT_DIRS):
        out.append(Finding("warn", id,
            f"points at {path}, outside {'/ '.join(OUTPUT_DIRS)}/"))

    by = rec.get("origin", {}).get("by")

    want = rec.get("hash")
    if not want:
        out.append(Finding("error", id, "has no hash"))
    elif _sha(target) != want:
        if by == "adopted":
            # No generator will ever refresh this hash, so acceptance has to be
            # explicit -- the same contract as a changed pinned file.
            out.append(Finding("error", id,
                f"{path} has changed since it was adopted. If the change is "
                f'deliberate, re-record it: just adopt note="..."'))
        else:
            out.append(Finding("error", id,
                f"{path} has changed since it was generated. It is written by "
                f"{rec.get('origin', {}).get('by', 'a script')}; a hand-edit to it "
                f"survives until the next `just assets` and then vanishes."))

    if not by:
        out.append(Finding("error", id, "has no origin.by"))
    elif by == "adopted":
        # Adopted: nothing can rebuild it, by declaration. The note is the
        # audit trail, exactly as for a hand-entered number in stats.json,
        # and is required for the same reason.
        if not (rec.get("origin", {}).get("note") or "").strip():
            out.append(Finding("error", id,
                "is adopted but has no origin.note. Say where the file came "
                "from -- a repository, a collaborator, a previous submission. "
                "An adopted file with no provenance is just an unclaimed file "
                "with paperwork."))
    elif not (ROOT / by).is_file():
        out.append(Finding("error", id,
            f"was generated by {by}, which no longer exists. Nothing can "
            f"rebuild {path}: restore the script, or adopt the file as-is "
            f'(just adopt note="...") if the analysis is gone for good.'))

    for src, want_hash in sorted((rec.get("inputs") or {}).items()):
        p = ROOT / src
        if not p.is_file():
            # Not a failure: analysis/data/ is normally untracked, so this is the
            # ordinary state of a fresh clone.
            out.append(Finding("note", id, f"input {src} is not present, so it "
                                           f"could not be verified"))
        elif _sha(p) != want_hash:
            out.append(Finding("error", id,
                f"input {src} has changed since {path} was generated -- "
                f"run: just assets"))
    return out


def _references(values: dict) -> list[Finding]:
    """Ids the manuscript calls but does not declare, and the reverse.

    The first direction is already a compile failure -- fig() panics on an
    unknown id -- so this catches it earlier and with a better message. The
    second is the one nothing else sees: an asset that is still generated and
    still hashed, and that no sentence points at any more.
    """
    src = " ".join(re.sub(r"//[^\n]*", " ", p.read_text())
                   for p in sorted(ROOT.glob("*.typ")))
    called = set(CALL.findall(src))
    out = [Finding("error", id, "is referenced by the manuscript but not "
                                "declared in assets.json -- run: just assets")
           for id in sorted(called - set(values))]
    out += [Finding("warn", id, "is declared but no .typ file references it")
            for id in sorted(set(values) - called)]
    return out


def _unclaimed(values: dict) -> list[Finding]:
    """A file under figures/ or si/ that no entry claims.

    The case this is for: a generator is deleted, its output stays on disk and
    stays referenced, and it silently never updates again. Nothing else notices,
    because every other check reasons from the entries rather than the files.

    An ERROR rather than a warning, since .assets-stamp was removed: that hash
    covered this at full severity, and it is the one failure here that leaves a
    figure frozen in the manuscript with nothing able to refresh it.
    """
    claimed = {r.get("path") for r in values.values()}
    out: list[Finding] = []
    for d in OUTPUT_DIRS:
        folder = ROOT / d
        if not folder.is_dir():
            continue
        for f in sorted(folder.rglob("*")):
            if not f.is_file() or f.name.startswith(".") or f.suffix == ".pyc":
                continue
            rel = f.relative_to(ROOT).as_posix()
            if rel not in claimed:
                out.append(Finding("error", rel,
                    "is in a generated directory but no assets.json entry "
                    "claims it. Either a leftover from a deleted generator, a "
                    "script that does not call record() -- or a file whose "
                    "analysis is gone for good, which is adopted with "
                    '`just adopt note="..."`'))
    return out


def main() -> int:
    if not ASSETS.is_file():
        print("no assets.json: this manuscript declares no generated assets.")
        return 0
    try:
        doc = json.loads(ASSETS.read_text())
    except json.JSONDecodeError as e:
        print(f"assets.json is not valid JSON: {e}")
        return 1
    values = doc.get("values")
    if not isinstance(values, dict):
        print("assets.json has no `values` table; regenerate with `just assets`")
        return 1

    found: list[Finding] = []
    for id, rec in sorted(values.items()):
        found += _entry(id, rec)
    found += _references(values)
    found += _unclaimed(values)

    from report import findings
    findings([(f.level, f.id, f.msg) for f in found])
    errors = [f for f in found if f.level == "error"]
    adopted = sum(1 for r in values.values()
                  if r.get("origin", {}).get("by") == "adopted")
    print(f"  {len(values)} declared asset(s)"
          + (f", {adopted} adopted (nothing can regenerate them)" if adopted else "")
          + (f", {len(errors)} error(s)" if errors else ", no errors"))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
