#!/usr/bin/env python3
"""Render stats.json into the file Typst reads.

WHY THIS STEP EXISTS. Typst has no format-spec: no thousands separator, no
`+.2f`, no fixed decimals. Its `str()` also rounds floats where Python's does not
(`1.0899999999999999` is `1.09` there and the full expansion here), so the two
disagree about exactly the values a paper cares about.

The old answer was to store the rendered string in stats.json beside the value.
That is a derived field living in a source file: redundant, driftable, and it
needed its own check to catch an edit to one that no longer matched the other.

So the formatting moved into the build instead. stats.json holds the VALUE and
the FORMAT; this renders them with Python's formatter -- the only formatter in
the pipeline -- into stats-rendered.json, which is what stats.typ reads. Nothing
is stored twice, so nothing can drift, and there is no check needed for a
disagreement that can no longer happen.

stats-rendered.json is a build artifact and is gitignored. Every recipe that
compiles the manuscript regenerates it first, so it cannot be stale.

Run with `just render-stats`; the compile recipes depend on it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import typst_prose  # noqa: E402

SRC = ROOT / "stats.json"
OUT = ROOT / "stats-rendered.json"

ABOUT = ("GENERATED by tools/render_stats.py from stats.json -- do not edit, and "
         "do not commit. Edit stats.json, or the generator that writes it.")


def main() -> int:
    if not SRC.is_file():
        # Not an error: the generated-numbers mechanism is optional, and a
        # manuscript that deleted it must still build. stats.typ is deleted along
        # with stats.json in that case, so nothing will read the output either.
        #
        # The derived file is removed rather than left behind: a stale
        # stats-rendered.json outliving its source is a corpse a compile could
        # still read, which is the one way this step could serve stale numbers.
        if OUT.is_file():
            OUT.unlink()
            print(f"no stats.json: removed the stale {OUT.name}")
        else:
            print("no stats.json: nothing to render")
        return 0

    try:
        doc = json.loads(SRC.read_text())
    except json.JSONDecodeError as e:
        print(f"stats.json is not valid JSON: {e}", file=sys.stderr)
        return 1
    values = doc.get("values")
    if not isinstance(values, dict):
        print("stats.json has no `values` table; run: just assets", file=sys.stderr)
        return 1

    out = {}
    for id, rec in sorted(values.items()):
        try:
            shown = typst_prose.display_of(rec)
        except (TypeError, ValueError) as e:
            print(f"{id}: cannot format {rec.get('value')!r} with "
                  f"{rec.get('fmt', '')!r}: {e}", file=sys.stderr)
            return 1
        # Only what Typst needs: `s` reads display, `n` reads value. The unit,
        # guards, provenance and description are for the audit and for
        # check_stats.py, and stay out of the compile's way. `unit` stays in
        # stats.json as metadata about the value -- unlike the deleted `source`
        # it describes the number rather than duplicating its provenance -- but
        # nothing in the document reads it, so it is not rendered.
        out[id] = {"display": shown, "value": rec.get("value")}

    OUT.write_text(json.dumps({"_about": ABOUT, "values": out}, indent=2) + "\n")
    print(f"rendered {len(out)} value(s) -> {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
