// AUTO-GENERATED by scripts/gen_charge_table.py -- do not edit by hand.
#table(
  columns: 4,
  align: (left, right, right, right),
  table.header(
    [Charge], [Clusters], [Mean isotope score], [Share of TIC (%)],
  ),
  [1], [29], [0.918], [20.6],
  [2], [4], [0.724], [0.8],
  [3], [2], [0.620], [0.5],
  [4], [3], [0.659], [0.7],
  [unassigned], [419], [--], [77.5],
)
