#!/usr/bin/env python3
"""Write si/charge_table.typ: the demo spectrum's clusters broken down by charge.

The bare `#table(...)` contract: no caption, no label, nothing but the table.
si-body.typ wraps it in a `#figure` and supplies both, so the manuscript keeps
control of the numbering and the cross-reference.

Picked up by `just assets` on the filename pattern gen_*_table.py.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from _assets import record
from _demo import DATA_FILES, PAPER, demo_spectra

OUT = PAPER / "si" / "charge_table.typ"

HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"


def main() -> int:
    raw, decon, _ = demo_spectra()
    tic = float(raw.intensity.sum())

    rows: list[tuple[str, str, str, str]] = []
    for z in sorted({int(c) for c in decon.charge if c > 0}):
        sel = decon.charge == z
        rows.append((
            str(z),
            str(int(sel.sum())),
            f"{float(np.mean(decon.iso_score[sel])):.3f}",
            f"{100 * float(decon.intensity[sel].sum()) / tic:.1f}",
        ))

    # The total row is computed from the UNROUNDED sum, so it renders the same
    # number the prose states as demo.tic_share; the per-charge rows above are
    # rounded one at a time and need not sum to it. The caption says both.
    assigned = decon.charge > 0
    rows.append((
        "all assigned",
        str(int(assigned.sum())),
        f"{float(np.mean(decon.iso_score[assigned])):.3f}",
        f"{100 * float(decon.intensity[assigned].sum()) / tic:.1f}",
    ))

    # The unassigned peaks belong in the table too. A charge-state breakdown that
    # silently omits them reads as though the deconvolution explained everything.
    # A singleton is an individual PEAK left unmerged, not a cluster, so the
    # cell says "peaks" rather than borrowing the Clusters column's unit.
    sing = decon.charge < 0
    rows.append((
        "unassigned",
        f"{int(sing.sum())} peaks",
        "--",
        f"{100 * float(decon.intensity[sing].sum()) / tic:.1f}",
    ))

    lines = [
        HEADER,
        "#table(\n",
        "  columns: 4,\n",
        "  align: (left, right, right, right),\n",
        "  table.header(\n",
        "    [Charge], [Clusters], [Mean isotope score], [Share of TIC (%)],\n",
        "  ),\n",
    ]
    for row in rows:
        lines.append("  " + ", ".join(f"[{v}]" for v in row) + ",\n")
    lines.append(")\n")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record(
        "tbl.charge",
        str(OUT.relative_to(PAPER)),
        kind="table",
        inputs=DATA_FILES,
        desc="Clusters, mean isotope score and TIC share per assigned charge state",
    )
    print(f"wrote {OUT.relative_to(PAPER)}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
