// =============================================================================
// Manuscript skeleton. Edit config.typ for the title/authors/abstract, then
// replace the placeholder sections below with real prose.
//
// DO NOT delete the "BODY START" / "BODY END" marker comments. Three separate
// tools slice the prose out of this file at those markers -- the word counter,
// the readability report, and the audiobook narrator -- and each fails loudly
// rather than guessing if they go missing.
//
// The docx-mode machinery in this preamble is load-bearing for `just docx` and
// is inert on the PDF path. Read the comments before changing it.
// =============================================================================

#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "config.typ": *
// Numbers generated by the analysis, read as #s("id"). See stats.typ. Delete
// this import along with stats.typ, stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": lit, n, s, todo
// Generated figures and tables, referenced as #fig("id") / #tbl("id"). See
// assets.typ. Delete this import along with assets.typ and assets.json if the
// project includes no generated figures or tables.
#import "assets.typ": fig, tbl

// Word-export path (`just docx`): compiling with --input docx=true bypasses the
// arkheion template. Its front matter and heading styling are built from layout-only
// primitives (page/pad/line/block) that Typst's HTML export discards, which silently
// drops every section heading and the abstract. In docx mode we skip the template and
// emit plain front matter instead, so headings survive as real <h2>/<h3> elements.
// With the flag absent this is inert and the PDF is byte-for-byte unchanged.
#let docx-mode = sys.inputs.at("docx", default: "") == "true"

#let _template = arkheion.with(
  title: paper-title,
  authors: paper-authors,
  abstract: paper-abstract,
  keywords: paper-keywords,
  date: paper-date,
)

// Apply the template for PDF; in docx mode pass the document through untouched.
#show: if docx-mode { doc => doc } else { _template }

// arkheion normally supplies heading numbering; without it the `@sec:` cross-references
// fail to resolve, so restore it on the docx path only. The SI's own "S1"-style
// numbering is set later in the file and still overrides this for the appendix.
#set heading(numbering: "1.") if docx-mode

// Typst's HTML export drops equations outright, which would gut any sentence built
// around inline math. html.frame keeps each one as an SVG that typst2docx.py then
// rasterizes back inline. Identity on the PDF path, so print output is unchanged.
#show math.equation: it => if docx-mode { html.frame(it) } else { it }

// Front matter for the Word/HTML path only (the template would normally supply it).
// The author line comes from config.typ, built from the same author list the PDF
// template uses, so the superscript affiliation markers cannot drift.
#if docx-mode {
  text(17pt, weight: "bold", paper-title)
  parbreak()
  text(11pt, paper-author-line)
  parbreak()
  for (i, affil) in paper-affiliations.enumerate() {
    text(9pt, style: "italic", super(str(i + 1)) + " " + affil)
    linebreak()
  }
  parbreak()
  text(10pt, strong("Abstract.") + " " + paper-abstract)
  parbreak()
  text(9pt, strong("Keywords: ") + paper-keywords.join(", "))
}

// Print just a cross-reference's number (e.g. "3") with no "Figure"/"Table"/
// "Section" prefix, for enumerations like "Figures 2 and 3".
#let refn(l) = ref(l, supplement: none)

// >>> BODY START -- everything from here to BODY END is counted as prose and narrated.

= Summary

Mass spectrometry generates spectra whose peaks are not the quantities an
analyst reasons about. A tryptic peptide arrives as an isotopic envelope spread
over several m/z values at an unknown charge, sitting on a noise floor, and the
question asked of it is about one neutral mass. The steps between those two
representations, denoising, isotope deconvolution, charge assignment, neutral
mass conversion, fragment matching and scoring, are standard, and are
reimplemented in nearly every analysis script that needs them.

*spxtacular* is a Python library that provides those steps as methods on a
single chainable `Spectrum` object. That object carries m/z and intensity
alongside optional per-peak charge, ion mobility, and isotopic profile score.
What one step learns is therefore available to the next, rather than returned as
a parallel array the caller has to keep in register.

```python
neutral = (spec.denoise(method="mad")
               .deconvolute(charge_range=(1, 4), tolerance=15,
                            tolerance_type="ppm", min_score=0.5)
               .decharge())
```

@fig:abstract shows that chain applied to one real MS2 scan, each stage drawn by
the library itself.

#figure(
  fig("fig.abstract", width: 100%),
  caption: [
    The pipeline on one real MS2 scan, every panel drawn by the library: the
    spectrum as read (left), its isotope clusters coloured by assigned charge
    (middle), and the neutral masses `decharge()` returns (right).
  ],
) <fig:abstract>

A `SpectrumType` tag records whether the object holds profile, centroid or
deconvoluted data, and guards the operations that make sense in only one of
those states. Calling `decharge()` on a spectrum that was never deconvoluted
raises an error instead of silently returning wrong masses. The library depends
only on NumPy @harris2020numpy, pandas, Plotly, and two companion packages for
peptide chemistry and fragment notation.

= Statement of need

Existing Python tooling for proteomics divides along a line that leaves a gap in
the middle. File format libraries such as pyteomics @levitsky2019pyteomics and
pyOpenMS @rost2014pyopenms read spectra and hand back arrays, and the processing
is the user's problem. Search engines and deconvolution tools such as MS-Deconv
@liu2010msdeconv and FLASHDeconv @jeong2020flashdeconv are complete programs,
not libraries: they are excellent at the one job they do and are difficult to
call in the middle of an interactive analysis. Between the two sits the work of
actually looking at a spectrum, which is where method development happens and
where most bespoke scripts are written.

spxtacular targets that middle. Deconvolution is a method call that returns a
spectrum, not a subprocess that returns a file, so its output can be filtered,
plotted, matched against fragments and fed back into another deconvolution
inside one session. Charge and isotope score travel with the peaks, so the
quality of an assignment stays inspectable. A weakly scoring cluster stays
distinguishable from a convincing one in a filter and in a plot; nothing
upstream has flattened the two into one accept or reject decision.

The library also treats visualization as part of the analysis, not a reporting
step bolted on afterwards. Every spectrum plots itself, and all figures share
one theme whose palettes were validated for protanopia and deuteranopia against
both light and dark backgrounds. Charge state is encoded as an ordinal ramp,
because a cycling categorical palette of ten colors draws the first and the
eleventh state identically. Intensities are shown relative to the base peak by
default. A `table_view()` helper renders the same peak data as an HTML table for
screen reader users.

= Deconvolution

Isotope cluster detection follows the greedy strategy that MS-Deconv and THRASH
@horn2000thrash established, with scoring made explicit and per-peak. The
algorithm seeds on the most intense unused peak. For each state in the requested
range it extends a candidate cluster forward in steps of one neutron mass
divided by that state, then scores the candidate against a theoretical isotope
distribution using the Bhattacharyya coefficient. Detectable peaks that are
missing from the envelope are penalized, and the best scoring state wins.
Clusters falling below `min_score` are recorded as singletons rather than
discarded, and their peaks stay available to later seeds.

The score survives into the result as `iso_score`, so the threshold is a filter
the user controls, not a constant compiled into the algorithm. The spectrum in
@fig:abstract makes the effect concrete: tandem mass spectrometry (MS2) scan #s(
  "demo.scan",
) of the Bruker timsTOF example acquisition shipped with the library,
deconvoluted over charges one to #s("demo.max_charge_searched") at #s(
  "demo.tolerance_ppm",
) ppm tolerance. Of #s("demo.raw_peaks") centroid peaks, #s(
  "demo.cluster_peaks",
) resolved into #s("demo.clusters") charge-assigned clusters carrying #s(
  "demo.tic_share",
) of the total ion current at a mean isotope score of #s("demo.mean_score").
States as high as #s("demo.max_charge_found") were assigned, and `decharge()`
returned #s("demo.neutral_masses") neutral masses up to #s(
  "demo.max_neutral_mass",
) Da.

= Reading files and interoperating

`Reader` dispatches on the path suffix to Bruker timsTOF `.d` directories, mzML
@martens2011mzml, and Thermo `.raw` files. Every backend yields the same
`MsnSpectrum` type, with scan number, retention time, precursors, collision
energy and ion mobility filled in where the format carries them. MGF and MS2
peak lists are read and written with no optional dependency at all. The
vendor-specific readers are optional extras, so a downstream package can depend
on spxtacular without pulling in a .NET runtime it will never use.

Fragment matching accepts fragments from the companion peptacular library, which
implements ProForma #lit("2.0") @leduc2018proforma, and labels matched peaks in
mzPAF notation. Scoring covers the hyperscore that X!Tandem popularized
@craig2004tandem and the normalized spectral contrast angle
@toprak2014spectralangle, alongside the matched fraction and error statistics a
method paper usually reports. A spectrum can be serialized to a compact URL safe
token, which makes a specific spectrum citable in an issue or a message without
attaching a file.

= State of the field

matchms @huber2020matchms addresses a neighboring problem, spectrum to spectrum
similarity for metabolomics, and shares the goal of a processing pipeline
expressed as composable steps. spectrum_utils @bittremieux2023spectrumutils
covers annotation and plotting of identified spectra with a similar emphasis on
visualization quality. spxtacular differs from both in making charge state
deconvolution a first class operation whose per-peak evidence is retained, and
in reading vendor formats directly instead of starting from an already converted
peak list. It complements both packages and interoperates with them through the
same community standards, mzML, ProForma, mzPAF and the Universal Spectrum
Identifier @deutsch2021usi.

// <<< BODY END

#heading(numbering: none)[Associated Content]

*Availability*

spxtacular is released under the MIT license, published on PyPI as `spxtacular`,
and developed at #link("https://github.com/tacular-omics/spxtacular"). The
documentation, including the API reference and the guides the examples here are
drawn from, is at #link("https://tacular-omics.github.io/spxtacular"). The
Supporting Information is appended to this document.

*Author Contributions*

P.T.G. designed and implemented the library and wrote the manuscript. J.R.Y.
supervised the work and revised the manuscript.

*Notes*

The authors declare no competing financial interest.

#heading(numbering: none)[Acknowledgment]

Funding and acknowledgments go here.

#bibliography("references.bib", title: [References], style: paper-bib-style)

// ===================== Supporting Information (appendix) =====================
// The SI is appended here as an appendix so the whole manuscript is a single
// compilation with one label namespace -- every @fig/@tbl/@sec resolves across
// the main text and the SI, and numbers can never drift out of sync.
// From this point on, figures and tables restart at S1, S2, ... and SI headings
// number S1, S2, ...  (page and line numbering stay continuous.)
#pagebreak()

#counter(figure.where(kind: image)).update(0)
#counter(figure.where(kind: table)).update(0)
#counter(heading).update(0)
#show figure.where(kind: image): set figure(numbering: n => "S" + str(n))
#show figure.where(kind: table): set figure(numbering: n => "S" + str(n))
#set heading(numbering: (..n) => "S" + n.pos().map(str).join("."))

// Same trap as any centred block: HTML export discards the align/block wrapper AND
// its contents, so on the Word path this whole title block vanishes and the main
// text runs straight into Section S1 with nothing marking the boundary. Emit it as
// plain content there -- a real heading, so it also lands in Word's navigation pane
// -- and keep the centred layout for the PDF.
#if docx-mode [
  #heading(level: 1, numbering: none, outlined: false)[Supporting Information]

  #text(13pt)[#paper-title]

  #text(10pt, style: "italic")[#si-authors]
] else [
  #align(center)[
    #text(15pt, weight: "bold")[Supporting Information]
    #v(2pt)
    #text(13pt)[#paper-title]
    #v(2pt)
    #text(10pt, style: "italic")[#si-authors]
  ]

  #v(1em)
]

#include "si-body.typ"
