// Supporting Information body -- included by paper.typ as an appendix (single
// combined document, one label namespace, so @fig/@tbl/@sec resolve across the
// main text and the SI). The SI title, page/margin setup, and S-prefixed
// numbering (Figure/Table/Section "S" prefixes) are all applied by paper.typ at
// the include site. This file is body-only and is NOT compiled on its own.
//
// Tables under si/ are auto-generated by the scripts in scripts/; never edit
// them by hand. See scripts/gen_charge_table.py for the contract.

// Print just a cross-reference's number (e.g. "S2") with no "Table"/"Figure"
// prefix, for enumerations like "Tables S1 and S2".
#let refn(l) = ref(l, supplement: none)

// Numbers generated by the analysis, read as #s("id"). Imported HERE as well as
// in paper.typ because `include` gives this file its own scope: it does not
// inherit the importing file's bindings, so without this line an #s("id") in the
// SI fails with `unknown variable: s` even though paper.typ imports it.
#import "stats.typ": lit, n, s, todo
#import "assets.typ": fig, tbl

The Supporting Information records the deconvolution result the main text
summarizes, broken down by charge state, and the exact commands that reproduce
every number and the figure in this paper.

= Deconvolution by charge state <sec:si-charge>

@tbl:si-charge is the per-charge view of the run described in the main text: MS2
scan #s("demo.scan") of the example Bruker timsTOF acquisition, deconvoluted
over charges one to #s("demo.max_charge_searched") at #s("demo.tolerance_ppm")
ppm. Clusters scoring below #s("demo.min_score") are recorded as singletons
rather than kept. The precursor was selected at charge #s(
  "demo.precursor_charge",
), and singly charged fragments dominate the assigned clusters, which is what a
collision induced dissociation spectrum of a tryptic peptide should look like.

Most peaks stay unassigned, and most of the total ion current stays with them.
That is the honest result for a single MS2 scan rather than a defect: an
unpaired peak is one for which no second isotope was detected above the noise,
so no charge can be inferred from spacing alone. Those peaks keep a charge of
minus one and a score of zero, and remain available to fragment matching, which
does not require a charge assignment.

#figure(
  tbl("tbl.charge"),
  caption: [
    Clusters, mean isotope profile score and share of the total ion current for
    each assigned charge state in the demo spectrum, with the unassigned
    singletons shown on the last row. Written by
    `analysis/scripts/gen_charge_table.py`.
  ],
) <tbl:si-charge>

= Reproducibility <sec:si-repro>

Every number and the figure in this paper are produced by running spxtacular #s(
  "lib.version",
) on data committed to its own repository, so nothing here depends on a file the
reader cannot open.

The input is `tests/data/example_dda.d`, the Bruker timsTOF DDA acquisition the
library uses as a test fixture. The analysis that reads it lives in
`paper/analysis/` inside the same repository. Its dependency set is locked, and
it takes spxtacular from the working tree rather than from PyPI, so the paper
describes the code beside it rather than a release that may have moved on.

```bash
git clone https://github.com/tacular-omics/spxtacular
cd spxtacular/paper
just assets     # regenerate the figure, the table and every number
just paper      # compile the PDF
just joss       # emit paper.md and paper.bib for submission
just verify     # check that all of the above agree with their sources
```

The pipeline parameters are defined once, in `analysis/scripts/_demo.py`, and
read from there by the figure, the table and the numbers, so the three cannot
describe different runs. `just verify` re-runs each declared value against the
guard recorded beside it, and compares every generated file against the hash of
the inputs it was built from. A stale figure or a drifted number is therefore a
build failure, not something a reader has to notice.
